toptext = "PIZZA CRAWLER\n(ORIGINALLY BY MCPIG)\n\n\nDIRECTOR\nMARIOS REALITY\n\n\nCODERS\nMARIOS REALITY\nFIRERED\nQUANTUMV\n\n\nCOMPOSER\nTHE NOSE\n\n\nARTISTS\nGOOBER\nYUCKIE\n\nORIGINAL PIZZA CRAWLER SOUNTRACK\nMR SAUCEMAN\nDAYPEECONE\nDISCHU\n\n AND A SPECIAL THANKS\nTO THE TESTERS\nIN THE PIZZA CRAWLER DISCORD"
scroll = 900
tilex = 1
tiley = 1
scrollspr = spr_pause_bg
drawsplash = 0
set_state((2 << 0))
